# 扩展样板供应器总槽位容量的倍率。
# 基础为36，每页仍显示36格，倍率会增加总页数/总容量。
# 建议范围 1-16
pageMultiplier: 16

# 设置AE构建合成计划过程中的 wait/notify 次数，提升吞吐但会降低调度响应性
craftingPauseThreshold: 100000

# 无线收发器最大连接距离（单位：方块）
# 从端与主端的直线距离需小于等于该值才会建立连接
wirelessMaxRange: 256.0

# 是否允许无线收发器跨维度建立连接
# 开启后，从端可连接到不同维度的主端（忽略距离限制）
wirelessCrossDimEnable: true

# 智能倍增时是否对样板供应器轮询分配
# 仅多个供应器有相同样板时生效，开启后请求会均分到所有可用供应器，关闭则全部分配给单一供应器
# 注意：所有相关供应器需开启智能倍增，否则可能失效
providerRoundRobinEnable: true

# 全局智能倍增的最大倍率限制（0 表示不限制）
# 此限制针对单次样板产出的倍增上限，用于控制一次推送的最大缩放规模
# 优先级低于样板自身的供应器限制
smartScalingMaxMultiplier: 0

# 是否显示样板编码玩家
# 开启后将在样板 HoverText 上添加样板的编码玩家
showEncoderPatternPlayer: true

# 样板终端默认是否显示槽位
# 影响进入界面时SlotsRow的默认可见性，仅影响客户端显示
patternTerminalShowSlotsDefault: true

# 实体加速器能量消耗基础值
entityTickerCost: 512

# 是否优先从磁盘提取FE能量（仅当Applied Flux模组存在时生效）
# 开启后，将优先尝试从磁盘提取FE能量；反之优先消耗AE网络中的能量
prioritizeDiskEnergy: true

# 实体加速器黑名单：匹配的方块将不会被加速。支持通配符/正则（例如：minecraft:*）
# 格式：全名或通配符/正则字符串，例如 'minecraft:chest'、'minecraft:*'、'modid:.*_fluid'
entityTickerBlackList:

# 额外消耗倍率配置：为某些方块设置额外能量倍率，格式 'modid:blockid multiplier'，例如 'minecraft:chest 2x'
# 支持通配符/正则匹配（例如 'minecraft:* 2x' 会对整个命名空间生效）。
entityTickerMultipliers:

