
["Mekanism升级设置"]
	#机器可接受的最大速度/能量升级数量，重启游戏生效
	#Range: 1 ~ 64
	"最大升级数量" = 64
	#速度升级增强倍率
	#Range: > 1
	"速度平均每8个升级最终效果乘以一次该倍率" = 1
	#能量升级节电增强倍率
	#Range: > 1
	"节电平均每8个升级最终效果乘以一次该倍率" = 1
	#能量升级储电增强倍率
	#Range: > 1
	"储电平均每8个升级最终效果乘以一次该倍率" = 1

["维度生成设置"]
	#边框方块，若不存在则使用蓝色羊毛
	"边框方块" = "useless_mod:aqua_glow_plastic"
	#填充方块，若不存在则使用白色羊毛
	"填充方块" = "useless_mod:white_glow_plastic"
	#中心方块，若不存在则使用灰色羊毛
	"中心方块" = "useless_mod:light_gray_glow_plastic"

["游戏机制设置"]
	#植物盆生长倍率 - 1.0为原版速度，2.0为2倍速度
	#Range: > 1
	"植物盆生长倍率（仅限非附属的植物盆）" = 1
	#矩阵样板槽位倍数 - 减少数量时请保持槽位空！否则可能会造成样板丢失
	#Range: 1 ~ 100
	"矩阵样板槽位倍数" = 1

	["游戏机制设置"."牛排工具设置"]
		#连锁挖掘的X轴范围半径
		#Range: 1 ~ 32
		"连锁挖掘X轴范围" = 32
		#连锁挖掘的Y轴范围半径
		#Range: 1 ~ 32
		"连锁挖掘Y轴范围" = 32
		#连锁挖掘的Z轴范围半径
		#Range: 1 ~ 255
		"连锁挖掘Z轴范围" = 255
		#连锁挖掘的最大方块数量
		#Range: 1 ~ 10000
		"连锁挖掘最大方块数量" = 10000
		#牛排工具时运附魔等级
		#Range: 1 ~ 127
		"牛排工具时运等级" = 100
		#牛排工具抢夺附魔等级
		#Range: 1 ~ 127
		"牛排工具抢夺等级" = 100

["Thermal Parallel 设置"]
	#如果设置为true，则机器的能耗会随并行增多而成倍增加
	"并行增加能耗" = false
	#如果设置为true，则机器的并行数量会被整合组件带来的基础倍率增幅
	"基础倍率影响并行" = false
	#如果设置为true，则更高等级的并行插件会被加进创造模式物品栏
	"添加额外并行增强到标签" = false
	#如果设置为true，则并行升级会同步提高机器的输入/输出物品存储上限
	"并行增加物品容量" = true
	#如果设置为true，则并行升级会同步提高机器的流体存储上限
	"并行增加流体容量" = true
	#如果设置为true，则并行升级会同步提高机器的能量存储上限
	"并行增加能量容量" = false
	#如果设置为true，则并行升级会同步提高机器进行自动提取/弹出物品的速率上限
	"并行增加物品传输" = true
	#如果设置为true，则并行升级会同步提高机器进行自动提取/弹出流体的速率上限
	"并行增加流体传输" = true
	#如果设置为true，则并行升级会同步提高机器的能量传输上限
	"并行增加能量传输" = true

